In [1]:
import numpy as np

数组

In [2]:
a = np.array([1,2,3,4])

In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array((1,2,3,4))

In [5]:
a = np.array([[1,2,3],[4,5,6]])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b = [[1,2,3],[4,5,6]]

In [8]:
a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [9]:
b + b

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [10]:
a + a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
b * 2

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [13]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
b * b

TypeError: can't multiply sequence by non-int of type 'list'

In [15]:
a * a

array([[ 1,  4,  9],
       [16, 25, 36]])

数组的属性：

In [16]:
a.shape

(2, 3)

In [17]:
c = np.array([1,2,3])

In [18]:
c.shape

(3,)

In [19]:
np.shape(a)

(2, 3)

In [20]:
b

[[1, 2, 3], [4, 5, 6]]

In [21]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

In [22]:
np.shape(b)

(2, 3)

In [23]:
np.shape(123)

()

标量 形状是一个空元祖

In [24]:
a.dtype

dtype('int32')

data type数据类型

In [28]:
[1,2,"sad",[1,2,3,4]]

[1, 2, 'sad', [1, 2, 3, 4]]

In [29]:
a.itemsize

4

In [30]:
a.size

6

In [31]:
np.size(a)

6

In [32]:
np.size(b)

6

In [33]:
a.nbytes

24

In [34]:
a.ndim

2

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a.fill(7.3)

In [37]:
a

array([[7, 7, 7],
       [7, 7, 7]])

In [38]:
a.dtype

dtype('int32')

类型：

In [39]:
a = np.array([1,2,3,4])

In [40]:
a.dtype

dtype('int32')

In [42]:
a = np.array(1,'d')

In [43]:
a.dtype

dtype('float64')

In [45]:
a = np.array([1,2,3+2j,4,0])

In [46]:
a.dtype

dtype('complex128')

imag 虚部 real 实部

In [49]:
a.imag

array([0., 0., 2., 0., 0.])

In [50]:
a.real

array([1., 2., 3., 4., 0.])

In [51]:
a.conj()

array([1.-0.j, 2.-0.j, 3.-2.j, 4.-0.j, 0.-0.j])

In [52]:
a = np.array([1,2,"123"])

In [53]:
a.dtype

dtype('<U11')

In [54]:
a

array(['1', '2', '123'], dtype='<U11')

In [60]:
a = np.array([1,2,"123"],dtype=int)

In [56]:
a

array([  1,   2, 123])

In [57]:
a.dtype

dtype('int32')

```python
bool,int,float,complex,str,
np.float32,np.float64,np.int32,np.int64
"float","int","float32"
```

In [61]:
a = np.array([1,2,"123",[1,2]])

ValueError: setting an array element with a sequence

In [62]:
a = np.array([1,2,"123",[1,2]],dtype=object)

In [63]:
a.shape

(4,)

In [64]:
a

array([1, 2, '123', list([1, 2])], dtype=object)

In [65]:
a * 2

array([2, 4, '123123', list([1, 2, 1, 2])], dtype=object)

In [66]:
a = np.array([1,2,3])

In [68]:
np.array(a,dtype=float)

array([1., 2., 3.])

In [69]:
np.asarray(a,dtype=float)

array([1., 2., 3.])

In [72]:
np.array(a,dtype=int) is a

False

In [73]:
np.asarray(a,dtype=int) is a

True

In [74]:
a.astype(float)

array([1., 2., 3.])

In [75]:
a

array([1, 2, 3])

无穷大：

In [76]:
np.inf

inf

不合法的数，not a number(nan)

In [77]:
np.nan

nan

In [79]:
a = np.array([1,-1,0])

In [80]:
a/0

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf, -inf,  nan])

数组的生成：

In [81]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [83]:
a = np.zeros((2,3))

In [84]:
a.shape

(2, 3)

In [85]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
a = np.ones((2,3))

In [90]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [91]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [93]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [94]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
np.arange(1,10.0,2.5)

array([1. , 3.5, 6. , 8.5])

In [96]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [97]:
a = np.linspace(0,10)

In [98]:
a

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [99]:
a.shape

(50,)

索引：

In [100]:
a = np.arange(5)

In [101]:
a

array([0, 1, 2, 3, 4])

In [102]:
a[0]

0

In [103]:
a[-1]

4

In [104]:
a[1:]

array([1, 2, 3, 4])

In [105]:
a[1::2]

array([1, 3])

In [106]:
a = np.arange(20)

In [107]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [108]:
a.shape

(20,)

In [109]:
a.shape=4,5

In [110]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [111]:
a.ndim

2

In [112]:
a[1,2]

7

In [113]:
a[0]

array([0, 1, 2, 3, 4])

In [114]:
a[0][0]

0

In [115]:
a[-1,-1]

19

In [116]:
a[0,-1]

4

In [117]:
a[:,1]

array([ 1,  6, 11, 16])

In [118]:
a[1:3,1]

array([ 6, 11])

In [119]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [120]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [123]:
for i in a:
    print(i)
    print(type(i))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[5 6 7 8 9]
<class 'numpy.ndarray'>
[10 11 12 13 14]
<class 'numpy.ndarray'>
[15 16 17 18 19]
<class 'numpy.ndarray'>


In [124]:
for idx,v in np.ndenumerate(a):
    print(idx,v)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9
(2, 0) 10
(2, 1) 11
(2, 2) 12
(2, 3) 13
(2, 4) 14
(3, 0) 15
(3, 1) 16
(3, 2) 17
(3, 3) 18
(3, 4) 19


数组的操作：

In [126]:
a.sum()

190

In [127]:
a.sum(axis=0)

array([30, 34, 38, 42, 46])

In [128]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [129]:
a.sum(axis=1)

array([10, 35, 60, 85])

In [130]:
a.shape

(4, 5)

In [131]:
b = np.arange(100)

In [132]:
b.shape = 2,5,10

In [133]:
b.ndim

3

In [134]:
b.sum(axis = 0)

array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])

In [135]:
a.argmax(axis=1)

array([4, 4, 4, 4], dtype=int64)

In [136]:
a.argmin(axis=1)

array([0, 0, 0, 0], dtype=int64)

In [137]:
a.argmin()

0

In [139]:
a.argmax()

19

In [140]:
a = a*2

In [141]:
a.argmin()

0

In [142]:
a.argmax()

19

In [143]:
a.mean()

19.0

In [144]:
a.mean(axis=1)

array([ 4., 14., 24., 34.])

特殊的索引：

In [145]:
a.shape

(4, 5)

In [146]:
a[:,None,:].shape

(4, 1, 5)

In [147]:
a.shape

(4, 5)

In [148]:
a.T

array([[ 0, 10, 20, 30],
       [ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38]])

In [149]:
a.T.shape

(5, 4)

拼接：

In [151]:
a = np.arange(6)
b = np.arange(10,16)
a.shape=2,3
b.shape=2,3

In [153]:
np.concatenate([a,b]).shape

(4, 3)

In [154]:
np.concatenate([a,b],axis=0).shape

(4, 3)

In [155]:
np.concatenate([a,b],axis=1).shape

(2, 6)

In [156]:
c = np.arange(3)

In [159]:
c.shape = 1,3

In [160]:
c

array([[0, 1, 2]])

In [162]:
np.concatenate([a,c],axis=0).shape

(3, 3)

In [163]:
np.concatenate([a,c],axis=1).shape

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [164]:
a.shape

(2, 3)

In [165]:
c.shape

(1, 3)

In [166]:
np.vstack((a,b)).shape # vertical

(4, 3)

In [167]:
np.hstack((a,b)).shape

(2, 6)

In [169]:
np.dstack((a,b)).shape

(2, 3, 2)

运算：

In [170]:
a = np.array([[1,2],[3,4]])

In [171]:
a+1

array([[2, 3],
       [4, 5]])

In [172]:
a+a

array([[2, 4],
       [6, 8]])

In [173]:
a/a

array([[1., 1.],
       [1., 1.]])

In [174]:
a/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [175]:
a-a

array([[0, 0],
       [0, 0]])

In [176]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [177]:
a**a

array([[  1,   4],
       [ 27, 256]], dtype=int32)

In [178]:
a%2

array([[1, 0],
       [1, 0]], dtype=int32)

矩阵：

In [179]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [180]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [181]:
a @ a

array([[ 7, 10],
       [15, 22]])

In [182]:
a

array([[1, 2],
       [3, 4]])

In [183]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [185]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [186]:
a>3

array([[False, False],
       [False,  True]])

In [187]:
if np.all(a>3):
    print('hi')

In [188]:
if np.all(a>0):
    print('hi')

hi


In [189]:
if np.any(a>3):
    print('hi')

hi


In [190]:
a = np.array([1.,2.])

In [191]:
a

array([1., 2.])

In [192]:
a == a

array([ True,  True])

数组广播机制：

In [196]:
a = np.array([[0,1],[0,1],[0,1]])
b = np.array([[1,1],[2,2],[3,3]])

In [197]:
a

array([[0, 1],
       [0, 1],
       [0, 1]])

In [198]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [199]:
a+b

array([[1, 2],
       [2, 3],
       [3, 4]])

In [200]:
a.shape

(3, 2)

In [201]:
a = np.array([0,1])

In [202]:
a.shape

(2,)

In [203]:
b.shape

(3, 2)

In [204]:
a+b

array([[1, 2],
       [2, 3],
       [3, 4]])

In [208]:
b = np.array([[1],[2],[3]])

In [209]:
b.shape

(3, 1)

In [210]:
a+b

array([[1, 2],
       [2, 3],
       [3, 4]])

两个数组维度不一样，低维的前面补1

如果维度一样，看每个维度的形状
- 形状一样
- 其中一个为1

数组广播的机制（Boardcasting）

a:256,256,3
b:3

a:256,256,3
b:1,1,3

a+b:256,256,3

花式索引，fancy indexing

In [216]:
a = [1,2,3,4,5]

In [217]:
a[[1,3,4]]

TypeError: list indices must be integers or slices, not list

In [213]:
a = np.array([1,2,3,4,5])

In [214]:
a[[1,3,4]]

array([2, 4, 5])

随机数组：

In [218]:
np.random.rand(2,3) #均匀分布

array([[0.16341253, 0.95291935, 0.41594144],
       [0.95674948, 0.75041058, 0.5897149 ]])

In [219]:
np.random.randn(2,3) #正态分布

array([[ 0.16704737,  0.21451724, -0.80393786],
       [ 0.3234957 , -0.42132148, -2.30604197]])