In [1]:
import numpy as np
import scipy.stats

In [5]:
a = np.array([1.56,1.87,1.90,2.1,1.3,1.3])

In [3]:
a.max()

2.1

In [4]:
a.min()

1.3

In [7]:
r = scipy.stats.mode(a) #众数 mode

In [8]:
r

ModeResult(mode=array([1.3]), count=array([2]))

In [9]:
r.mode

array([1.3])

In [12]:
r.count

array([2])

In [13]:
scipy.stats.skew(a) #偏度

-0.03346256215475293

In [14]:
scipy.stats.kurtosis(a) #峰度

-1.560229204649697

In [15]:
from scipy.stats import norm

In [18]:
x_norm = norm.rvs(size=(2,3))

In [19]:
x_norm

array([[ 0.83136259,  2.28315881, -0.3707838 ],
       [-0.3920107 , -0.22519766, -0.11324777]])

In [20]:
from scipy.stats import expon

In [21]:
expon.rvs(size=(2,3))

array([[0.0163427 , 0.99652   , 0.08731166],
       [0.91441259, 2.80088678, 0.61321087]])

积分：

In [22]:
from scipy.integrate import quad

In [23]:
x = np.linspace(0,np.pi)

In [24]:
quad(np.sin,0,np.pi)

(2.0, 2.220446049250313e-14)

In [25]:
from scipy import linalg

In [26]:
a = np.array([[1,2],[3,4]])

In [27]:
a

array([[1, 2],
       [3, 4]])

In [28]:
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])